function makeReplayButton(fig, env, states, rewards)
% delete old replay buttons
oldBtn = findall(fig, 'Type', 'uicontrol', 'Tag', 'ReplayButton');
delete(oldBtn);
uicontrol('Parent', fig, ...
          'Style', 'pushbutton', ...
          'String', 'Replay', ...
          'Tag', 'ReplayButton', ...
          'FontSize', 12, ...
          'Units', 'pixels', ...
          'Position', [20 20 100 35], ...
          'Callback', @(src,event) replayRollout(fig, env, states, rewards));
end